[I 06:07:46.131 LabApp] JupyterLab extension loaded from /usr/local/lib/python3.6/site-packages/jupyterlab
[I 06:07:46.131 LabApp] JupyterLab application directory is /usr/local/share/jupyter/lab
[I 06:07:46.134 LabApp] Serving notebooks from local directory: /mnt/nas6/M10815022/Workshop/MRQA-2019/ipynb
[I 06:07:46.134 LabApp] The Jupyter Notebook is running at:
[I 06:07:46.134 LabApp] http://localhost:8888/?token=3a32367d1a451d9b1fc53bdfe36d40771f7b16de9ac255a7
[I 06:07:46.134 LabApp]  or http://127.0.0.1:8888/?token=3a32367d1a451d9b1fc53bdfe36d40771f7b16de9ac255a7
[I 06:07:46.134 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 06:07:46.145 LabApp] 
    
    To access the notebook, open this file in a browser:
        file:///home/M10815022/.local/share/jupyter/runtime/nbserver-28912-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=3a32367d1a451d9b1fc53bdfe36d40771f7b16de9ac255a7
     or http://127.0.0.1:8888/?token=3a32367d1a451d9b1fc53bdfe36d40771f7b16de9ac255a7
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/%{ <-- HERE (.*?)}/ at /usr/bin/run-mailcap line 528.
[29390:29390:0714/060804.539257:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
Warning: program returned non-zero exit code #1
Opening "/home/M10815022/.local/share/jupyter/runtime/nbserver-28912-open.html" with Chromium Web Browser  (text/html)
[29400:29400:0714/060804.701392:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
[29646:29646:0714/060810.858879:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
/usr/bin/xdg-open: line 778: firefox: command not found
/usr/bin/xdg-open: line 778: iceweasel: command not found
/usr/bin/xdg-open: line 778: seamonkey: command not found
/usr/bin/xdg-open: line 778: mozilla: command not found
/usr/bin/xdg-open: line 778: epiphany: command not found
/usr/bin/xdg-open: line 778: konqueror: command not found
[29675:29675:0714/060810.946547:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
/usr/bin/xdg-open: line 778: google-chrome: command not found
[?1049h[1;24r(B[m[4l[?7h[?1h=[39;49m[39;49m[37m[40m[H[2J[37m[40m[J(B[m[39;49m[37m[40m[39;49m(B[m[22d(B[0;1m[33m[44mGetting file://localhost/home/M10815022/.local/share/jupyter/runtime/nbserver-2[K[39;49m(B[m

[24;1H[?1049l[?1l>[I 06:08:13.370 LabApp] 302 GET /?token=3a32367d1a451d9b1fc53bdfe36d40771f7b16de9ac255a7 (::1) 1.07ms
[I 06:08:13.892 LabApp] 301 GET /lab/workspaces/auto-f/?clone (::1) 1.92ms
[W 06:08:14.658 LabApp] Could not determine jupyterlab build status without nodejs
[W 06:08:15.057 LabApp] 404 GET /api/contents/Untitled.ipynb?content=0&1594721296837 (::1): No such file or directory: Untitled.ipynb
[W 06:08:15.058 LabApp] No such file or directory: Untitled.ipynb
[W 06:08:15.058 LabApp] 404 GET /api/contents/Untitled.ipynb?content=0&1594721296837 (::1) 2.35ms referer=http://localhost:8888/lab/workspaces/auto-f?clone
[I 06:08:15.154 LabApp] New terminal with automatic name: 1
TermSocket.open: 1
TermSocket.open: Opened 1
[I 06:08:33.692 LabApp] Creating new notebook in /
[I 06:08:33.971 LabApp] Kernel started: 990a83c6-8576-485b-9f71-2014b8fb3c03
[I 06:10:33.931 LabApp] Saving file at /EDA.ipynb
[I 06:12:34.247 LabApp] Saving file at /EDA.ipynb
[I 06:13:18.437 LabApp] Saving file at /EDA.ipynb
[I 06:15:18.562 LabApp] Saving file at /EDA.ipynb
[I 06:17:18.811 LabApp] Saving file at /EDA.ipynb
[I 06:19:19.016 LabApp] Saving file at /EDA.ipynb
[I 06:21:19.260 LabApp] Saving file at /EDA.ipynb
[I 06:23:19.479 LabApp] Saving file at /EDA.ipynb
[I 06:24:50.418 LabApp] Kernel restarted: 990a83c6-8576-485b-9f71-2014b8fb3c03
[I 06:25:19.698 LabApp] Saving file at /EDA.ipynb
[I 06:27:19.914 LabApp] Saving file at /EDA.ipynb
[I 06:29:20.140 LabApp] Saving file at /EDA.ipynb
[I 06:31:01.896 LabApp] Kernel restarted: 990a83c6-8576-485b-9f71-2014b8fb3c03
[I 06:31:20.377 LabApp] Saving file at /EDA.ipynb
[I 06:33:20.615 LabApp] Saving file at /EDA.ipynb
[I 06:35:20.722 LabApp] Saving file at /EDA.ipynb
[I 06:35:57.865 LabApp] Saving file at /EDA.ipynb
[I 06:36:03.617 LabApp] Saving file at /EDA.ipynb
[W 06:37:17.573 LabApp] 404 GET http://clientapi.ipip.net/echo.php?info=1234567890 (::1) 68.10ms referer=None
[I 06:38:03.714 LabApp] Saving file at /EDA.ipynb
[I 06:42:03.813 LabApp] Saving file at /EDA.ipynb
[I 06:44:03.947 LabApp] Saving file at /EDA.ipynb
[I 06:46:04.052 LabApp] Saving file at /EDA.ipynb
[I 06:48:04.198 LabApp] Saving file at /EDA.ipynb
[I 06:50:04.307 LabApp] Saving file at /EDA.ipynb
[I 06:52:04.430 LabApp] Saving file at /EDA.ipynb
[I 06:52:10.592 LabApp] Starting buffering for 990a83c6-8576-485b-9f71-2014b8fb3c03:3fb51b0f-82d8-44d5-b138-926f343472e7
Websocket closed
[W 06:53:42.618 LabApp] Could not determine jupyterlab build status without nodejs
TermSocket.open: 1
TermSocket.open: Opened 1
[W 06:53:44.646 LabApp] Could not determine jupyterlab build status without nodejs
[W 06:53:44.938 LabApp] 404 GET /api/contents/Untitled.ipynb?content=0&1594724026350 (::1): No such file or directory: Untitled.ipynb
[W 06:53:44.938 LabApp] No such file or directory: Untitled.ipynb
[W 06:53:44.939 LabApp] 404 GET /api/contents/Untitled.ipynb?content=0&1594724026350 (::1) 1.51ms referer=http://localhost:8888/lab
TermSocket.open: 1
TermSocket.open: Opened 1
Websocket closed
[I 06:53:56.687 LabApp] Kernel restarted: 990a83c6-8576-485b-9f71-2014b8fb3c03
[I 06:55:43.993 LabApp] Saving file at /EDA.ipynb
[I 06:57:44.223 LabApp] Saving file at /EDA.ipynb
[I 06:57:47.437 LabApp] Saving file at /EDA.ipynb
[I 06:59:47.542 LabApp] Saving file at /EDA.ipynb
[I 07:01:02.600 LabApp] Saving file at /EDA.ipynb
